name: json_generator
description: >-
  Just the pubspec for the json_generator.dart file
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'
  
dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.6.1
  test: '>=1.15.0 <2.0.0'